version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    command: ["serve", "-s", "dist", "-l", "3000"]

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:ceyda@db:5432/todo_app
    depends_on:
      - db
    command: ["node", "dist/index.js"]

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ceyda
      POSTGRES_DB: yourdb
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
